apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: opentest
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21.5-alpine
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
