apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21.5-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      request:
        memory: "64Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
