apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplo
  namespace: opentest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deplo
  template:
    metadata:
      labels:
        app: deplo
    spec:
      containers:
      - name: deplo
        image: nginx:1.21.5-alpine
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
        - mountPath: /usr/share/nginx/html
          name: html
        ports:
        - containerPort: 80
      initContainers:
      - command:
        - sh
        - -c
        - echo 'hello world' > /html/index.html
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        name: init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /html
          name: html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - emptyDir: {}
        name: html
